module.exports = {
    NOT_FOUND_ERR: 'Not found',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    RECORD_NOT_FOUND: 'Record not found',
    EMAIL_IS_EXIST: 'Email is exist',
    EMAIL_OR_PASSWORD_ERR: 'Email or password is wrong',
    WRONG_TOKEN: 'Wrong token',
    NO_TOKEN: 'No token',
    ACCESS_DENIED: 'Access denied',
    TEMPLATE_NOT_FOUND: 'Template not found',
    VALIDATION_ERR: 'Validation failed',
    ACCOUNT_NOT_ACTIVE: 'Account is not active',
    FILE_EXTENSION_ERR: 'File extension not valid',
    LARGE_FILE_ERR: 'File is too large',
    CORS_ERR: 'Cors not allowed',
};
